### PR TITLE
atenergy computes the harmonic number from the RF frequency

### PR DESCRIPTION
**Pull request by lfarv**
`atenergy` does not rely any more on the `HarmNumber` field of cavity elements. It computes the harmonic number from the frequency of the 1st RF cavity.

### CODE REVIEW

**Comment by carmignani** [comment]
Hello, I think the harmonic number is stored in the ringParam element, if that exists. So maybe atenergy should first check there, and after it can computes from the frequency of the first cavity if there is no ringParam element.

**Comment by lfarv** [comment]
@carmignani : excellent remark. I'll do that.

**Comment by simoneliuzzo** [comment]
may also the radiation state of the ring could be added to atGetRingParam ?

**Comment by simoneliuzzo** [comment]
and may be also the dp/p and RF shift of the the ring?

**Comment by lfarv** [comment]
@simoneliuzzo: in principle, I agree.But practically, "RingProperties" is an image of what is stored in the RingParam element. It is difficult to store there information which may be modified without going through `atSetRingProperties`: the stored information would the become wrong. In your examples, one could imagine that `atradon/off` would call `atSetRingProperties` to update the information. For dp/p or RF frequency it's more difficult…
Let's keep this for future.

**Comment by lfarv** [comment]
The upgrade is now more ambitious: `atenergy` now calls `atGetRingProperties`. This eliminates duplicated computations and has some benefits: for voltage and harmonic number, they are no more computed from the 1st cavity, but from the set of cavities with the lowest frequency (considered as "fundamental", even if it's not always true). This choice can be modified by setting the optional "`cavpts`" ring property.

**Review by simoneliuzzo — APPROVED** [review]

**Pull request merged**
