### PR TITLE
atx gives also the damping partition numbers

### PR DESCRIPTION
**Pull request by carmignani**
I added the function DampJfromTau and I call that function from atx to compute the damping partition numbers using the damping times.

### CODE REVIEW

**Comment by carmignani** [comment]
Automatic test failed. @willrogers, do you understand why? I changed only matlab code.

**Comment by willrogers** [comment]
A Travis failure - I restarted the job and it passed this time.

**Comment by lfarv** [comment]
Unless the function dampinJFromTau is useful somewhere else, I am not sure the computation is worth a dedicated function… It could be removed

**Comment by carmignani** [comment]
I agree, it can be removed. I had that function in my local AT since a long time ago and I just added the function, but I can delete it now.

**Pull request merged**
