### PR TITLE
Non linear

### PR DESCRIPTION
**Pull request by swhite2401**
Hello, following the benchmark done by Teresia I have fixed a number of bugs.
Everything looks OK comparing hmba.mat in pyAT and matlab.

I take the occasion to introduce and new label "WIP" to separate ongoing work w.r.t to the ready to go pull requests

### CODE REVIEW

**Comment by lcarver** [comment]
A few commits made, first a bug fix for the orbit argument in quantdiff. Second a simple block of code that merges all cavities with the same frequency. This also fixes a bug where the length of the cavity element was not modified (so it's length was taken into account twice). 

A comparison of the linear model between at and pyat was very accurate. For the non-linear model there is a small difference (of 1 or 2%) in the detuning element that arises from the fact that the tune computation is done differently between at and pyat (interpolated fft vs harmonic analysis).

Below I am making a comparison of Lmatp for the ESRF design lattice (without splitting). 

```
matarr = np.array([[1.2647, 0,0,0,        0,         0],
    [0.0005,    0.0677  ,       0    ,     0    ,     0      ,   0],
         [0     ,    0     ,    0  ,       0   ,      0  ,       0],
         [0    ,     0    ,     0   ,      0   ,      0    ,     0],
   [-2.4162  ,  0.0771    ,     0   ,      0  , 32.8531  ,       0],
   [-0.0869  ,  0.0038  ,       0    ,     0 ,   1.1809 ,   0.6807]])*1e-6
```

```
pyatmat =array([[ 1.25918335e+00,  0.0,  0.0, 0.0,  0.0,  0.0],
       [ 4.63247317e-04,  6.78938656e-02,  0.0, 0.0,  0.0,  0.0],
       [ 0.0,  0.0,  0.0, 0.0,  0.0,  0.0],
       [ 0.0,  0.0,  0.0, 0.0,  0.0,  0.0],
       [-2.44507133e+00,  6.92938192e-02,  0.0, 0.0,  3.28289354e+01,  0.0],
       [-8.75369515e-02,  3.79432645e-03,  0.0, 0.0,  1.17842180e+00,  6.79298772e-01]])*1e-6

```
The numbers are very close but not exact. Looking at the delta:

```
array([[-5.51665007e-09,  0.0,  0.0, 0.0,  0.0,  0.0],
       [-3.67526826e-11,  1.93865635e-10,  0.0, 0.0,  0.0,  0.0],
       [ 0.0,  0.0,  0.0, 0.0,  0.0,  0.0],
       [ 0.0,  0.0,  0.0, 0.0,  0.0,  0.0],
       [-2.88713297e-08, -7.80618080e-09,  0.0,  0.0, -2.41646041e-08,  0.0],
       [-6.36951492e-10, -5.67355323e-12,  0.0, 0.0, -2.47819627e-09, -1.40122785e-09]])

```
I think it looks fine. For sure this is closer than what it was before so its good for me but we can look closer for discrepancies once we start tracking with fastring.

**Review by lcarver — APPROVED** [review]

**Comment by lcarver** [comment]
As another check, I ran the following script:

```
ring = at.load_mat('./S28F.mat', key='LOW_EMIT_RING_INJ')
ring = at.Lattice(ring)
ring.radiation_off(quadrupole_pass='auto')

split_inds = [ ]
[ring_rg, ring_rg_rad] = fast_ring(ring, split_inds=split_inds)

num_particles = 10000
mu, sigma = 0, 50e-6 # mean and standard deviation
xdist = np.random.normal(mu, sigma, num_particles)
ydist = np.random.normal(mu, sigma, num_particles)

rin = np.zeros((6,num_particles))
rin[0,:] = xdist
rin[2,:] = ydist
rout = lattice_pass(ring_rg_rad, rin.copy(), nturns=50000) 

x_lastturn = rout[0,:,0,-1] #6,N,R,T
y_lastturn = rout[2,:,0,-1] #6,N,R,T
delta_lastturn = rout[4,:,0,-1]

sigmax_lastturn = np.std(x_lastturn)
sigmay_lastturn = np.std(y_lastturn)
sigmad_lastturn = np.std(delta_lastturn)

ld0, _, _, _ = ring_rg.linopt(get_chrom=True)
dispx = ld0['dispersion'][0]
dispy = ld0['dispersion'][1]
betax = ld0['beta'][0]
betay = ld0['beta'][1]
alphax = ld0['alpha'][0]
alphay = ld0['alpha'][1]

emitx = (sigmax_lastturn**2 - (sigmad_lastturn*dispx)**2)/betax
emity = (sigmay_lastturn**2 - (sigmad_lastturn*dispy)**2)/betay

ring.radiation_on(quadrupole_pass='auto')
t = ring.envelope_parameters()

print(t.emittances[0], t.emittances[1])
print(emitx, emity)

```
output:
tracking emitx = 1.3216608585797443e-10 
tracking emity = 2.8624489468700166e-40
ohmi emitx = 1.3047978839625594e-10 
ehmi emity = 3.7752251070430655e-19

This number could be refined in my opinion (more turns, more particles). But we are seeing basically the same equilibrium emittance.

**Comment by lcarver** [comment]
As another check, I ran the following script:

```
ring = at.load_mat('./S28F.mat', key='LOW_EMIT_RING_INJ')
ring = at.Lattice(ring)
ring.radiation_off(quadrupole_pass='auto')

split_inds = [ ]
[ring_rg, ring_rg_rad] = fast_ring(ring, split_inds=split_inds)

num_particles = 10000
mu, sigma = 0, 50e-6 # mean and standard deviation
xdist = np.random.normal(mu, sigma, num_particles)
ydist = np.random.normal(mu, sigma, num_particles)

rin = np.zeros((6,num_particles))
rin[0,:] = xdist
rin[2,:] = ydist
rout = lattice_pass(ring_rg_rad, rin.copy(), nturns=50000) 

x_lastturn = rout[0,:,0,-1] #6,N,R,T
y_lastturn = rout[2,:,0,-1] #6,N,R,T
delta_lastturn = rout[4,:,0,-1]

sigmax_lastturn = np.std(x_lastturn)
sigmay_lastturn = np.std(y_lastturn)
sigmad_lastturn = np.std(delta_lastturn)

ld0, _, _, _ = ring_rg.linopt(get_chrom=True)
dispx = ld0['dispersion'][0]
dispy = ld0['dispersion'][1]
betax = ld0['beta'][0]
betay = ld0['beta'][1]
alphax = ld0['alpha'][0]
alphay = ld0['alpha'][1]

emitx = (sigmax_lastturn**2 - (sigmad_lastturn*dispx)**2)/betax
emity = (sigmay_lastturn**2 - (sigmad_lastturn*dispy)**2)/betay

ring.radiation_on(quadrupole_pass='auto')
t = ring.envelope_parameters()

print(t.emittances[0], t.emittances[1])
print(emitx, emity)

```
output:
tracking emitx = 1.3216608585797443e-10 
tracking emity = 2.8624489468700166e-40
ohmi emitx = 1.3047978839625594e-10 
ehmi emity = 3.7752251070430655e-19

This number could be refined in my opinion (more turns, more particles). But we are seeing basically the same equilibrium emittance.

**Comment by TeresiaOlsson** [comment]
Sorry for the delay. I have repeated my comparison between AT and pyAT for the Diamond-I lattice now and it looks good. Most values agree or only start to differ around the sixth decimal. It's only the amplitude-dependent tune shifts that differ more, but not more than I think is expected.

### Without radiation:

**Nonlinear:**

Some differences for A1, A2 and A3.

  | AT 2.0 | pyAT
-- | -- | --
Betax | 9.69546145229164 | 9.69546145229164
Betay | 5.94412838275876 | 5.94412838275876
Alphax | -0.0422000227639180 | -0.0422000227639180
Alphay | 0.00871111863937026 | 0.00871111863937026
Qpx | 1.71078607649755 | 1.710787603248498
Qpy | 2.22018801659951 | 2.220186862134099
A1 | -3139.88990552111 | -3110.081508430372
A2 | 4374.95962951977 | 4305.9623051971985
A3 | 9086.15866547903 | 9141.301953919548
T1 | [0, 0, 0, 0, 0, 0] | [-0. -0. -0. -0. -0. -0.]
T2 | [0, 0, 0, 0, 0, 0] | [0. 0. 0. 0. 0. 0.]

### With radiation:

The change of closed orbit is now included.

**Linear:**

  | AT 2.0 | pyAT
-- | -- | --
L | 561.571000000003 | 561.571000000003
T1 | -3.15657511878141e-06   -2.28638677277481e-06   0   0   -0.000160189425733250   0.0387648939041058 | -3.15657542e-06   -2.28638703e-06   1.31169401e-30   -1.57933314e-31   -1.60189445e-04   3.87648985e-02
T2 | 3.15657511878035e-06   2.28638677277484e-06   0   0   -0.000168899252365091   -0.0387648939074068 | 3.15657542e-06   2.28638703e-06   1.13091103e-30   1.89599129e-31   -1.68899270e-04   -3.87648985e-02
I2 | 0.865728830889126 | 0.865728830889125

**Nonlinear:**

  | AT 2.0 | pyAT
-- | -- | --
Betax | 9.69546145229164 | 9.69546145229164
Betay | 5.94412838275876 | 5.94412838275876
Alphax | -0.0422000227639180 | -0.0422000227639180
Alphay | 0.00871111863937026 | 0.00871111863937026
Qpx | 1.71078607649755 | 1.710787603248498
Qpy | 2.22018801659951 | 2.220186862134099
A1 | -3139.88990552111 | -3110.081508430372
A2 | 4374.95962951977 | 4305.9623051971985
A3 | 9086.15866547903 | 9141.301953919548
T1 | -3.15657511878035e-06   -2.28638677277484e-06   0   0   0.000168899252365091   0.0387648939074068 | -3.15657542e-06   -2.28638703e-06   -1.13091103e-30   -1.89599129e-31   1.68899270e-04   3.87648985e-02
T2 | 3.15657511878035e-06   2.28638677277484e-06   0   0   -0.000168899252365091   -0.0387648939074068 | 3.15657542e-06   2.28638703e-06   1.13091103e-30   1.89599129e-31   -1.68899270e-04   -3.87648985e-02

**Comment by lcarver** [comment]
So if there are no further objections, i propose we merge this branch into the master.

**Comment by swhite2401** [comment]
ok for me

**Comment by willrogers** [comment]
We've done a lot of work making sure that Matlab and pyat give the same results.

I appreciate that they are a bit tricky, but ideally we would now write some of the matlab tests - these would make sure that we notice if the two implementations diverge in the future.

I know @lfarv can run the matlab tests, have you managed @lcarver or @swhite2401 ?

**Comment by swhite2401** [comment]
@willrogers , I haven't had time to look into it. Problems is our IT group does not want to do a global install as only few python versions are available.
I ll see how to integrate it in our virtual environment, meanwhile I don't think this should be blocking the merge since this was thoroughly tested and compared with matlab by several persons, also all the function used by fastring have their own individual test functions.

**Comment by swhite2401** [comment]
By the way @willrogers, @lfarv , is there such test functions for the matlab implementation? Discrepancies in the comparison could originate from matlab developments as well. In case the checks are done only on one side it may become very complicated to track errors back

**Comment by willrogers** [comment]
> I don't think this should be blocking the merge

Sure, these are just suggestions. I wrote some stuff about why the tests are good but then I deleted it, we all know tests are good. Please carry on with your merge.


I don't think there are any Matlab tests. I'll just say this very quietly and then I'll shut up: just because it's difficult to find the cause of discrepancies doesn't mean we shouldn't look for them...

**Comment by willrogers** [comment]
Realistically, yes, that would be a bit of a hassle.

Even better would be to be able to run these comparison tests on Travis or some other service. Then if either Matlab or Python changed then the test would fail on the pull request. I'm not sure that will be possible though.

**Comment by swhite2401** [comment]
That would be great indeed but I wouldn't know how to do that...

**Comment by lfarv** [comment]
I regularly run and update the Matlab tests. That's true it does not tell which one is wrong in case of disagreement, but it already proved good enough to spot errors in the Matlab version ! But there's a lot more to do then to have wider tests. 

@swhite2401 : The #177 branch from @lcarver was set to be merged into non-linear rather than master. Since it's now ready, can you merge it before merging non-linear into master ?

**Comment by lcarver** [comment]
the branch atbeam has been checked by @lfarv and I just merged it into non-linear. So for me this is ready to be merged.

**Pull request merged**
