### PR TITLE
Also scaling families in tune and chromaticity fits

### PR DESCRIPTION
**Pull request by swhite2401**
This PR introduces the possibility to fit tunes and chromaticities by scaling the families instead of adding a delta. This is useful in case a family is defined with several magnet types in order to keep their ratio constant.
The default behavior is unchanged

### CODE REVIEW

**Comment by simoneliuzzo** [comment]
dear @swhite2401 
this works perfectly for me!

**Review by simoneliuzzo — APPROVED** [review]

**Comment by simoneliuzzo** [comment]
The same applies for chromaticity?

**Comment by swhite2401** [comment]
Yes the same applies for chromaticity

**Comment by simoneliuzzo** [comment]
Tested also for chromaticity, I approve!

**Pull request merged**
