### PR TITLE
Bug correction in atcavityon and atcavityoff

### PR DESCRIPTION
**Pull request by carmignani**
There was a bug in the functions atcavityon and atcavityoff reported by TeresiaOlsson in #161.

### CODE REVIEW

**Comment by lnadolski** [comment]
This is indeed a bug.
The proposal  is fine.

Reviewing the file, I have found that the function atcavityoff should be modified furthermore to take into account cavities with nozero length.
I will update both files with the needed corrections.

**Comment by lfarv** [comment]
Reviewing again, I think that to avoid code duplication and different behaviours between `atcavityoff` and `atradoff`, we should simplify: for instance `atradoff` has the same bug as the initial `atcavityoff` with cavities with non-zero length.

So I suggest to:
- correct `atradoff`
- have `atcavityoff` call at `atradoff`, keeping other elements unchanged.
(and same for `atcavityon` of course)

If you allow me, I can propose such a version.

**Comment by lnadolski** [comment]
Dear @lfarv 

This is fine  with me. You can proceed as proposed.
We need nevertheless to keep some retrocompatibility in order not to break the running scripts in our respective labs.

Laurent.

**Comment by lnadolski** [comment]
Nevertheless, I suspect **something wrong the in the c-library**, since sometimes, the function returns NaNs for valid input signal.
If I rerun again the same command with the same input argument the results is then fine.
I suspect something not properly defined with the dynamic memory allocation in the code.

I need to run the code in debugger to understand. This is quite annoying and time consuming to debug.
Any advice is very welcome.

**Comment by lnadolski** [comment]
@lfarv 
I put a exmplae file for SOLEIL where radiation is can activated for all elements includes octupoles and multipoles

`function [ring,radelemIndex,cavitiesIndex,energy] = atradon(ring1,varargin)
%ATRADON switches RF and radiation on
%
%  [RING2,RADINDEX,CAVINDEX,ENERGY] = ATRADON(RING,CAVIPASS,BENDPASS,QUADPASS)
%    Changes passmethods to get RF cavity acceleration and radiation
%    damping. ATRADON also sets the "Energy" field on the modified elements,
%    looking for the machine energy in:
%       1) 1st 'RingParam' element
%       2) 1st 'RFCavity' element
%       3) field "E0" of the global variable "GLOBVAL"
%
%  INPUTS
%  1. RING	     initial AT structure
%  2. CAVIPASS   pass method for cavities (default CavityPass)
%                '' makes no change,
%  3. BENDPASS   pass method for bending magnets. Special values:
%                '' makes no change,
%                'auto' will substitute 'Pass' with 'RadPass' in any method
%                (default: 'auto')
%  4. QUADPASS   pass method for quadrupoles
%                '' makes no change,
%                'auto' will substitute 'Pass' with 'RadPass' in any method
%                (default: '')
%  5. SEXTUPASS   pass method for sextupoles
%                '' makes no change,
%                'auto' will substitute 'Pass' with 'RadPass' in any method
%                (default: '')
%  6. OCTUPASS   pass method for octupoles
%                '' makes no change,
%                'auto' will substitute 'Pass' with 'RadPass' in any method
%                (default: '')
%
%  OUPUTS
%  1. RING2     - Output ring
%  2. RADINDEX  - Indices of elements with radiation
%  3. CAVINDEX  - Indices of cavities
%  4. Energy    - Ring energy
%
%  See also ATRADOFF, ATCAVITYON, ATCAVITYOFF

[cavipass, bendpass, quadpass, sextupass, octupass]=parseargs({'CavityPass','auto','', '', ''},varargin);

ring = ring1;

% getenergy
energy=atenergy(ring);

%CAVITY business
if ~isempty(cavipass)
    cavitiesIndex=atgetcells(ring,'Frequency');
    if any(cavitiesIndex)
        ring(cavitiesIndex)=changepass(ring(cavitiesIndex),cavipass,energy);
    end
else
    cavitiesIndex=false(size(ring));
end

%BEND business
if ~isempty(bendpass)
    isdipole=@(elem,bangle) bangle~=0;
    dipoles=atgetcells(ring,'BendingAngle',isdipole);
    if any(dipoles) > 0
        ring(dipoles)=changepass(ring(dipoles),bendpass,energy);
    end
else
    dipoles=false(size(ring));
end

%QUADRUPOLE business
if ~isempty(quadpass)
    isquadrupole=@(elem,polyb) length(polyb) >= 2 && polyb(2)~=0;
    quadrupoles=atgetcells(ring,'PolynomB',isquadrupole) & ~dipoles;
    if any(quadrupoles) > 0
        ring(quadrupoles)=changepass(ring(quadrupoles),quadpass,energy);
    end
else
    quadrupoles=false(size(ring));
end

%SEXTUPOLE business
if ~isempty(sextupass)
    issextupole=@(elem,polyb) length(polyb) >= 3 && polyb(3)~=0;
    sextupoles=atgetcells(ring,'PolynomB',issextupole) & ~dipoles & ~quadrupoles;
    if any(sextupoles) > 0
        ring(sextupoles)=changepass(ring(sextupoles),sextupass,energy);
    end
else
    sextupoles=false(size(ring));
end

%OCTUPOLE business
if ~isempty(octupass)
    isoctupole=@(elem,polyb) length(polyb) >= 4 && polyb(4)~=0;
    octupoles=atgetcells(ring,'PolynomB',isoctupole) & ~dipoles & ~quadrupoles & ~sextupoles;
    if any(octupoles) > 0
        ring(octupoles)=changepass(ring(octupoles),octupass,energy);
    end
else
    octupoles=false(size(ring));
end

radelemIndex=dipoles|quadrupoles|sextupoles|octupoles;

if any(cavitiesIndex)
    atdisplay(1,['Cavities located at position ' num2str(find(cavitiesIndex)')]);
else
    atdisplay(1,'No cavity');
end
atdisplay(1,[num2str(sum(radelemIndex)) ' elements switched to include radiation']);

    function newline=changepass(line,newpass,nrj)
    if strcmp(newpass,'auto')
        passlist=atgetfieldvalues(line,'PassMethod');
        ok=cellfun(@(psm) isempty(strfind(psm,'RadPass')),passlist);
        passlist(ok)=strrep(passlist(ok),'Pass','RadPass');
    else
        passlist=repmat({newpass},size(line));
    end
    newline=cellfun(@newelem,line,passlist,'UniformOutput',false);

        function elem=newelem(elem,newpass)
            elem.PassMethod=newpass;
            elem.Energy=nrj;
        end
    end

end
`

**Comment by lfarv** [comment]
`atradon`/`atradoff` are corrected so that
- it fixes #161 (wrong pass method)
- it fixes #146 and #147 (safely turn radiation off)
- it allows turning on/off radiation in sextupoles and octupoles

`atcavityon`/`atcavityoff` now call `atradon`/`atradoff`

@lnadolski : initially, `atcavityon` was returning a logical mask of cavity locations. In the first updated versions, it was changed to an integer list of locations. I put back the output to logical mask, for retrocompatibility. Is this correct ?

**Comment by carmignani** [comment]
I just corrected a "DriftPassPass" with a "DriftPass".

**Comment by lfarv** [comment]
Thanks @carmignani .

I forgot to mention that the functions now accept cell array of character vectors (length 1 or equal to the number of magnets) for pass methods (since `atcavityon` allowed it). And also strings, string arrays etc.

`Lattice.radiation_on` and `Lattice.radiation_off` are now modified similarly:
- fixes #161 (wrong pass method)
- fixes #146 and #147 (safely turn radiation off)
- allows turning on/off radiation in sextupoles and octupoles

However I noted that these methods can also act on wigglers (`wiggler_pass` keyword). The same should be done in Matlab, but there the order of arguments is significant, and I would prioritise wigglers with respect to sextupoles and octuples, so that we would have `(ring,cavipass, bendpass,quadpass,wigglerpass,sextupass,octupass)`. In addition, I do not know yet how to isolate wigglers in the lattice. We could have wigglerpass temporarily inactive, with a warning, until we have a solution. What is your advice ?

**Comment by lfarv** [comment]
A final proposal to deal with the problems previously mentioned for the Matlab version:
- The positional arguments stay identical: `atradon(ring,cavipass,bendpass,quadpass)`. Backward compatibility ensured!
- new elements can be set with keyword arguments. Ex.: `atradon(…,'sextupass','auto')`. For consistency, the present positional arguments are also available as keywords. This has two advantages: you do not need to type the default arguments that you want to keep:
`atradon(ring,'quadpass','auto')` is simpler than `atradon(ring,'CavityPass','auto','auto')`,
and it allows to add new types when needed (wigglers).

@lnadolski, @carmignani : what do you think?

**Review by lfarv — APPROVED** [review]

**Pull request merged**
