### PR TITLE
Added average optics function calculation

### PR DESCRIPTION
**Pull request by swhite2401**
Hello,
I added the function avlinopt to linear.py, it is based on the matlab sr.model function used to compute the average beta,D and mu at chosen ring elements.
I did a comparison and it looks ok to me, please let me know in case you find something odd.
Cheers,
Simon

### CODE REVIEW

**Comment by lcarver** [comment]
Few things left undefined in the return.
I ran: 

```
ring = at.load_mat('./betamodel.mat', mat_key='betamodel')
ring = at.Lattice(ring)

ring.radiation_off(quadrupole_pass='auto')
res = at.avlinopt(ring)

```
and got an error:

`NameError: avespos is not defined `

**Comment by swhite2401** [comment]
I have fixed the bug with avespos not defined.
On the request of @lcarver

**Comment by lcarver** [comment]
Looks fine to me. Did a few tests of the different features, got what seemed to be sensible results out.

**Comment by lfarv** [comment]
I added in the Matlab tests a test of this new function. The agreement is better that 1.0e-20 on-momentum, but off-momentum I had to relax the tolerance to 1.0E-10 for the dispersion.

**Comment by swhite2401** [comment]
Hello Laurent,
Only the dispersion fails? That is odd...

**Comment by swhite2401** [comment]
Thanks Laurent! Sure if you have improvements they are more than welcome!

I thought pyat did not allow negative length, did that change?

**Comment by lfarv** [comment]
We had a discussion on negative lengths, they are useful and should work. But there may be problems somewhere, please report !

**Comment by lfarv** [comment]
Proposal for vectorised code.

**Comment by swhite2401** [comment]
Very nice! If you agree it is ok for me to merge.

Concerning negative lengths, it is just that I did not know you introduced it. So far, no problems on my side.

**Comment by lfarv** [comment]
I found a problem with refpts. I’ll correct as soon as I can get a computer…

**Pull request merged**
