### PR TITLE
Doxygen documentation

### PR DESCRIPTION
**Pull request by swhite2401**
This branch adds a doxygen automatically generated documentation to the python webpage.
It has to be built manually for the moment but can be added to the github actions on merge.

It order to look at the website you have to change the github settings such that the github pages are built from this branch and not the master

### CODE REVIEW

**Comment by lfarv** [comment]
Excellent !
The website is temporarily based on the doxy-doc branch and looks looks nice. But **don't delete the branch** !
If you are happy with this version, you can merge (without deleting the branch). Even if it can be improved, it's already much better now !
I'll be away again, starting to-morrow noon, for ~one week.

**Review by lfarv — APPROVED** [review]
Excellent !

**Comment by lfarv** [comment]
Did you document the procedure to build the oxygen doc ?
Should `doxygen` be added to the installation when specifying the `[dev]` option ?

**Comment by swhite2401** [comment]
I still have to look at details, but I have found some examples where the build is defined as a github action when merging a branch to the master.

For now I have installed `doxygen` locally, I don't know whether it has to be added to the AT installation. To build it you just need to run `doxygen Doxyfile` in `at/pyat`. I have edited the file such that it puts all the files in the right place.

To build the pdf you need to go in `docs/p/doxy/latex` and run `make`

and that's it basically.

The page does not look very nice, I am sure we can do much better, and I would like to explore the automated build so I leave this open for now.

Don't hesitate to contribute!

**Comment by lfarv** [comment]
Thanks, @swhite2401.
The instructions for manually building the doc (your 2 lines) could be in README file, stored in  `at/developer/doxigen` (for instance).
For sure, the home page could be nicer, but no urgency.

**Comment by swhite2401** [comment]
@lfarv, I have been looking a bit more in details and tuning the webpage is not straight forward, on the other hand Sphinx looks much more modern, I do not merge for now an set this one as a draft.

**Comment by swhite2401** [comment]
I closed this one

**Pull request closed without merging**
