### PR TITLE
Fix atplot for single-element lattices

### PR DESCRIPTION
**Pull request by lfarv**
This fixes a crash when using `atplot` on single-element lattices, as reported by @simoneliuzzo in #848

### CODE REVIEW

**Comment by simoneliuzzo** [comment]
Dear @lfarv,

I have tested this branch but it does not seem to solve the issue. 

Screenshot 2024-11-12 at 13 02 18

and here a test with input twiss

Screenshot 2024-11-12 at 13 05 14

thank you for looking into this and my apologies for taking so long time to test.

best regards
Simone

**Comment by lfarv** [comment]
@simoneliuzzo: sorry, I missed another problem.
You can try with this new version. Don't worry for delays, this branch is not blocking anything!

**Comment by simoneliuzzo** [comment]
Dear @lfarv,

now it seems ok!

It still gives error for ringparam and marker elements. But I think this is not an issue.

thank you
best regards
Simone

**Review by simoneliuzzo — APPROVED** [review]
tested, ok

**Comment by lfarv** [comment]
> It still gives error for ringparam and marker elements. But I think this is not an issue.

Yes, and it still gives error for empty lattices. But these cases have no real interest…

**Pull request merged**
