### PR TITLE
Unify the computation of radiation integrals in DipoleRadiation.py

### PR DESCRIPTION
**Pull request by willrogers**
@lfarv is this what you wanted?

### CODE REVIEW

**Comment by lfarv** [comment]
@willrogers : this does represent what the pull request should show, but can you put this back into the initial pull request to keep the links and comments, or do I have to copy everything ?

**Comment by willrogers** [comment]
I can force-push it to the `radiation_integrals` branch as long as you are happy that you won't lose anything.

**Comment by lfarv** [comment]
No, that's ok, let me know what you did, in case...

**Comment by willrogers** [comment]
I looked at the history and saw that the changes you made were all in one commit. I made a new branch from master and then 'cherry-picked' that commit on to the new branch.

```
git checkout master
git checkout -b radiation_integrals2
git cherry-pick 61e1011948bb8afcb83073301db7c2b5c941f55e
```

Now `radiation_integrals2` is the correct diff from `master`.

```
git checkout radiation_integrals
git reset --hard radiation_integrals2  # Change old branch to be the same as the new one
git push -f origin radiation_integrals   # Overwrite the old branch with my updated version
```

There's always lots of different ways to do things with git.

**Pull request closed without merging**
