### PR TITLE
Fix syntax errors

### PR DESCRIPTION
**Pull request by mfurseman**
I was attempting to build a compiled Matlab application against AT, however this failed as some files contained syntax errors. This provides the bare minimum necessary to resolve those errors.

### CODE REVIEW

**Comment by carmignani** [comment]
Hello, the file splitelem.m should be completely deleted in my opinion.
@simoneliuzzo @lfarv

**Comment by simoneliuzzo** [comment]
I agree for the file splitelem.m, it is not used, and it may not be used, as it is broken.

**Comment by mfurseman** [comment]
Thank you for your comments. I've pushed a commit to remove splitelem.m.

**Comment by carmignani** [comment]
We can merge the pull request, but first we should take the last change from the master!

**Comment by willrogers** [comment]
Done.

**Pull request merged**
