### PR TITLE
Update Collective.md

### PR DESCRIPTION
**Pull request by swhite2401**

### CODE REVIEW

**Comment by swhite2401** [comment]
@lcarver, I have started this branch for the documentation on collective effects, you can edit directly the `Collective.md` on the github page using the markdown syntax and see a preview.
To rebuild the webpage it has to be merged onto the master branch, we will do this at the end.
Please populate this page when you have time.

**Comment by swhite2401** [comment]
Outdated I closed it

**Comment by lfarv** [comment]
@swhite2401: are you sure you do not want to keep the `Collective.md` file ? It displays nicely with Sphinx, but I don't know if it is valid… If you really want to discard it, please also delete the branch, otherwise keep it for a future update;

**Comment by swhite2401** [comment]
It is valid yes, but is more or less a repetition of what is already in the docstring so I think we can discard it, we will come with something better with formulas etc... for now one can refer to the API doc
I delete the branch

**Pull request closed without merging**
