### PR TITLE
Fix load mat

### PR DESCRIPTION
**Pull request by lfarv**
This fixes a bug reported by @swhite2401 in #766.

### CODE REVIEW

**Comment by lfarv** [comment]
When this is approved, I will immediately publish a bug fix release 0.6.1. 
For this, the license in the project metadata is also fixed.

**Comment by lfarv** [comment]
For info, the .mat file contains strange attributes in the RingParam element. @swhite2401, can you remember if this file was created by a recent version?
Anyway these strange attributes are now ignored.

**Review by swhite2401 — COMMENTED** [review]
Thanks for the quick fix!
Question, can't we just assume that the lattice can have any attribute?

**Comment by swhite2401** [comment]
> For info, the .mat file contains strange attributes in the RingParam element. @swhite2401, can you remember if this file was created by a recent version? Anyway these strange attributes are now ignored.

This is an old version because this is the environment I create for FCC studies a while ago, can remember exactly when

**Review by swhite2401 — APPROVED** [review]

**Comment by lfarv** [comment]
>  can't we just assume that the lattice can have any attribute?

Yes, that's what it should be. The problem appeared with "deprecated attributes" which were kept for compatibility as properties. This created the bug and is now solved.

**Pull request merged**
