### PR TITLE
RDT computed also from multipole magnets

### PR DESCRIPTION
**Pull request by carmignani**
It is a very simple change. The function computeRDT uses now also the multipole magnets, not only quadrupoles, sextupoles and octupoles. 
plotRDT is also modified.

### CODE REVIEW

**Comment by lfarv** [comment]
It looks like the commits in this branch were applied to the master branch without merging. Can someone explain what happened ?

**Comment by lnadolski** [comment]
Hi Laurent,

This is due to one of my actions.
I wanted to get this commit on my working branch, but unfortunatly I did it on the master branch and published it.

I used 'git cherry-pick' command from the master branch.

Sorry for that action.

**Comment by lfarv** [comment]
Ok, then Nicola, I think you can delete the branch and close the pull request !

**Comment by carmignani** [comment]
Ok, I close this pull request

**Comment by surajsanh123** [comment]
I am new to the pyAT. I want to know how can I generate an octupole element?

**Comment by swhite2401** [comment]
Please have a look at the online documentation (Github webpage) there are examples of element generation, for the specific case of octupoles you may either use `at.Octupole` of `at.Multipole`:

`oct = at.Octupole(Name,Length,PolynomA,PolynomB)`

The last 2 arguments are the polynomial coefficients describing the field, for a normal octupole only the PolynomB[3] is non zero.

Side comment: commenting on closed branches is not efficient, in case of questions please ask then in the discussion section

**Pull request closed without merging**
