### PR TITLE
Added option 'RelativeShift' to atsetshift

### PR DESCRIPTION
**Pull request by carmignani**
I added the optional flag 'RelativeShift' to atsetshift and to atshiftelem to allow to add a displacement on top of the existing T1 and T2.

### CODE REVIEW

**Comment by simoneliuzzo** [comment]
In my opinion this change should go along with the same change in atsettilt and other error setting related functions. 
Also the default should remain absolute error setting for backward compatibility.

**Comment by carmignani** [comment]
Thanks @simoneliuzzo for your comment. I added the option 'RelativeTilt' to atsettilt, as you suggested. The default is for both tilt and shift an absolute error setting, not relative.
It would be good to add the same options to the python functions.

**Comment by lfarv** [comment]
For tilts: if the initial R1 and R2 are not pure rotations, the multiplications may not be commutative. R1 multiplication is now correct.
I added tests on flags: a typo in a flags would have it been silently ignored, with wrong results.

**Comment by lfarv** [comment]
Made the similar modification in python introducing the 'relative' keyword in
`shift_elem`, `tilt_elem`, `set_shift`, `set_tilt`

**Comment by willrogers** [comment]
I haven't checked the physics but this looks sensible to me.

**Comment by lfarv** [comment]
No real physics: just a convenient option for accumulating different kinds of errors!

**Pull request merged**
