### PR TITLE
Track functions

### PR DESCRIPTION
**Pull request by carmignani**
I created a branch called track_functions in order to convert the few integrators that still have the passFunction to the new format with the trackFunction, so they are faster and compatible with python AT.

### CODE REVIEW

**Comment by bnash** [comment]
Sorry, I don't have a lot of time to look at this at the moment.  But its nice to make all the pass methods use the trackfunction.  Nice that all python related tests are still passed, though I haven't looked in detail as to what they entail.

**Comment by carmignani** [comment]
@willrogers, do you know why two of the four python tests failed on Matrix66Pass.c?

**Comment by willrogers** [comment]
If you click through to find the failed jobs and then the log file ([here](https://ci.appveyor.com/project/willrogers/at-vswr6/build/1.0.45/job/8ipx3cauc01tl6h1)), you find the following at the end

```
Matrix66Pass.obj : error LNK2019: unresolved external symbol mxIsNaN referenced in function Matrix66Pass
build\lib.win-amd64-2.7\at\integrators\Matrix66Pass.pyd : fatal error LNK1120: 1 unresolved externals
error: command 'C:\\Users\\appveyor\\AppData\\Local\\Programs\\Common\\Microsoft\\Visual C++ for Python\\9.0\\VC\\Bin\\amd64\\link.exe' failed with exit status 1120
```

I think the problem is using `mxIsNaN` on line 22 of `Matrix66Pass.c` when you should be using `atIsNaN`.

**Comment by carmignani** [comment]
Ok, you are right! I will correct it.

**Pull request merged**
