### PR TITLE
Lattice tools

### PR DESCRIPTION
**Pull request by lfarv**
This is a proposal for classes used for matching, correction or simple characterisation of a lattice. We introduce the following classes:
- `Observables`, and sub-classes
- `Variables`, and sub-classes

Their use is tested in a prototype of `ResponseMatrix` classes.

This is proposal open for discussion an improvement. The corresponding documentation is available [here](https://at.readthedocs.io/en/latticetools/)

### CODE REVIEW

**Comment by lfarv** [comment]
Here is a Jupyter notebook showing the use of Observables (remove the .txt extension): 
[test_corr.ipynb.txt](https://github.com/atcollab/at/files/10796302/test_corr.ipynb.txt)
[test_corr.pdf](https://github.com/atcollab/at/files/10796304/test_corr.pdf)

**Comment by swhite2401** [comment]
Hello @lfarv, I had a quick look and it seems very nice! I think on the concept we have already agreed but now we need to look at details...

It is however an enormous piece of code to review and test....
You have asked several times in the past to have separate PRs for separate functionalities and I think it is necessary to apply the same to this one. Could you please split it in several pull requests such that we can test and validate the different features separately.

I can ca propose the following PRs:
-axisdef
-develop lattice
-variables
-observables
-matching (no done here but maybe the most relevant application for now -> may drive some modification to the PRs above)
-response (this will need a lot more inputs than just mine, I would hold onto this for now)

Thanks!

**Comment by lfarv** [comment]
@swhite2401 : good remark ! The main points hare are variables and observables. I had to look at matching and response matrices to be sure that the variables and observables, as they are now, would fulfil the needs:
- for response matrices, it's a very preliminary implementation, following yours
- for matching, I checked that nothing was apparently missing but I did not write anything…

All the rest are details…

So I'll split the PR as you propose.

**Comment by lfarv** [comment]
@swhite2401 : more precisely:

- I'll close this pull request #562,
- But I keep the `latticetools` branch because for development I need everything together, until some parts are approved. All the work will continue on that branch,
- I'll create specific branches for the topics you mentioned, and keep each of them in sync with the `latticetools` branch,
- I'll open one PR for each topic.

Is it OK like that ?

**Comment by swhite2401** [comment]
Sure! No problem. I do not have much time these days so smaller steps are easier to manage for me.

**Comment by lfarv** [comment]
#565 and #566 deal with some parts of this PR, other ones will follow, and I close this PR

**Pull request closed without merging**
