### PR TITLE
add collimator element

### PR DESCRIPTION
**Pull request by swhite2401**
This PR adds a Collimator element class that inherits from Aperture.

### CODE REVIEW

**Review by lfarv — APPROVED** [review]
No specific property for this element ?

**Comment by lfarv** [comment]
Side note:
It's very easy for any user to derive AT elements for his/her specific goals. You can imagine elements for valves, bellows, girder limits, and so on. This does not imply that these elements need to be integrated in the core of AT.

If such developments are worth sharing, there is the possibility of creating a dedicated repository for "user contributions". Long ago, the "pubtools" directory of AT was intended for that. However its contents have not been properly evaluated, it has a lot of missing references and is largely unusable. If this proves useful, it should be started again from scratch.

**Comment by swhite2401** [comment]
@lfarv this was requested by users, mostly to mimic was is done in MADX and facilitate conversion.
It think it makes sense, a Collimator does interfere with the beam as opposed to the other elements you mention.

I have to look, but thinking about it I think the aperture has to be forced to an `RAperture`, an elliptical aperture makes no sense for a colimator.

Concerning users contribution, I personally do not like it so much... `pubtools` turned out to become just some place to store just anything an in some cases unusable code, but that is my personal taste, I don;t have strong objection if you think this is useful

**Comment by swhite2401** [comment]
Changed collimator to drift with `RApertures `required

**Comment by lfarv** [comment]
> - Aperture allows for elliptical restriction (on choice)

`Aperture` is a rectangular aperture, `EAperture` is an elliptical aperture: an element does one thing, and does it right, as usual !

**Review by lfarv — APPROVED** [review]
Simple enough !

**Pull request merged**
