### PR TITLE
Wiggler changes

### PR DESCRIPTION
**Pull request by willrogers**
Continuation of #119.

I have got AP to do some testing and will update this branch with any necessary changes.

### CODE REVIEW

**Comment by willrogers** [comment]
AP at Diamond is now using this branch and are happy. I think we need to merge this, it has been open for a long time.

@lfarv @swhite2401 @carmignani @lnadolski

**Comment by willrogers** [comment]
@lfarv you mention documentation for pass methods, but I don't really see any documentation for any of them. Is #17 relevant?

**Comment by lfarv** [comment]
Concerning radiation integrals:
`ringpara` successively computes radiation integrals for
- dipoles in `CalRadInt`
- wigglers in `RadIntegrals`

For clarity, I would prefer renaming these to `DipoleIntegrals` and `WigglerIntegrals`. However, considering the discussion in #168, there is much more to do (having `atsummary` and `ringpara` consistent, using analytical integral instead of numerical...). So I suggest to keep it as it is for now, and open a new pull request to answer #168.

Concerning the Matlab wiggler creation functions: element creation functions like `drift`, `quadrupole`, `wiggler`… are replaced by `atdrift`, `atquadrupole`, `atwiggler`… and are kept for compatibility reason. So one should put back the deprecation warning which has been removed from `wiggler` and have `wiggler` call `atwiggler`, as it is done for other functions. Also `atwiggler` has small errors and could be re-written with the new standard for processing default values and keyword arguments (see `atquadrupole` for instance), but these are details…

Concerning documentation, this branch introduces new PassMethods for which the behaviour is not obvious: for instance, I do not see what `BndStrMPoleSymplectic4Pass` does (straight or bent?), I do not see how to use `ExactHamiltonianPass`, and, for wigglers, what are the pros and cons of `GWigSymplecticPass` versus `IdTablePass`. I agree that other ('well-known") PassMethods are not documented, but adding small `BndStrMPoleSymplectic4Pass.m` to provide help would be useful. But again, that is not blocking…

So go on , and I'll the open a new branch for radiation integrals in Matlab.

**Comment by willrogers** [comment]
I have addressed these comments as best I can and I will merge this once the tests have passed. If any problems have been introduced we will fix them as soon as possible.

**Pull request merged**
