### PR TITLE
Set the wiggler indivisible

### PR DESCRIPTION
**Pull request by lfarv**
This avoids a problem in plot_beta reported in #871 by setting a wiggler as "indivisible".

### CODE REVIEW

**Comment by lfarv** [comment]
@swhite2401: Not sure it works since I don't have a test case. Can you check?

**Comment by lfarv** [comment]
The fix in Matlab is much more delicate. I'll look at it…

**Comment by lfarv** [comment]
By the way, a "long" RF (rarely seen!) cavity has the same problem. If inactive, no problem, it's a drift. But if active, we should either set it "indivisible", or split the voltage!

**Comment by swhite2401** [comment]
Works on python!

**Comment by lfarv** [comment]
Fixed on Matlab too, ready for merging!

**Review by swhite2401 — APPROVED** [review]
I have tested matlab, but python works nicely!

**Pull request merged**
