### PR TITLE
Pyat

### PR DESCRIPTION
**Pull request by willrogers**
@bnash @lfarv @carmignani these changes should bring pyat up to date.

### CODE REVIEW

**Comment by bnash** [comment]
I see some tests are still running.  Nice to get all the Matlab and Python developments updated in one repository.

**Comment by bnash** [comment]
For practice with learning about pull requests, I assigned myself.
Any reason not to accept this pull request?

**Comment by willrogers** [comment]
Just check out the changes to the integrators, since they are most likely to affect other people.

Go to the Files Changed tab, then click Jump to... and type in atintegrators to help check out those specific files.

**Comment by bnash** [comment]
The changes were reviewed with @lfarv so we merge the pull request.

**Pull request merged**
