### PR TITLE
add EnergyLossRadPass to newmethods in atdiffmat.m

### PR DESCRIPTION
**Pull request by oscarxblanco**
Dear all,
this PR fixes an issue described in #865 , where the function atx fails to compute all parameters when there is an `EnergyLoss` in the ring.

The pass method `EnergyLossRadPass` is added to atdiffmat cell called `newmethods`.

### CODE REVIEW

**Comment by oscarxblanco** [comment]
Dear @swhite2401 and @lfarv ,
who could review this PR ?

**Comment by swhite2401** [comment]
Looks ok for me, but I am not very familiar with this

**Review by swhite2401 — APPROVED** [review]

**Comment by swhite2401** [comment]
Hello @oscarxblanco , in fact the python version is broken as well.... I add @lfarv as reviewer

**Comment by swhite2401** [comment]
> Hello @oscarxblanco , in fact the python version is broken as well.... I add @lfarv as reviewer

Same fix works in python too, we should integrate it in this PR

**Comment by lfarv** [comment]
@oscarxblanco, @swhite2401

I added the fix for python.

The change is OK, and allows to use ohmi_envelope with EnergyLoss. But there will be no diffusion computed for this element, so it will contribute to damping without introducing excitation.

If this is OK for you, you can go on and merge. @swhite2401; back tp you for approval…

**Review by swhite2401 — APPROVED** [review]

**Comment by lfarv** [comment]
@oscarxblanco: up to you for merging, if you agree with forgetting a possible diffusion which is impossible to compute without knowing the exact energy loss mechanism.

**Comment by lfarv** [comment]
This is fixed in #870 where these changes are included, among similar ones

**Pull request closed without merging**
